version: 2
plugins:
  - name: postgresql
    serviceId: letta_db_service
    envs:
      - name: PGUSER
        fromService:
          name: letta_db_service
          envKey: POSTGRES_USER
      - name: PGPASSWORD
        fromService:
          name: letta_db_service
          envKey: POSTGRES_PASSWORD
      - name: PGDATABASE
        fromService:
          name: letta_db_service
          envKey: POSTGRES_DB
      - name: PGHOST
        fromService:
          name: letta_db_service
          property: host
      - name: PGPORT
        fromService:
          name: letta_db_service
          property: port

services:
  letta_db_service:
    dockerComposeFile: railway-compose.yaml
    dockerComposeService: letta_db
    envs:
      - key: POSTGRES_USER
        value: ${LETTA_PG_USER:-letta}
      - key: POSTGRES_PASSWORD
        value: ${LETTA_PG_PASSWORD:-letta}
      - key: POSTGRES_DB
        value: ${LETTA_PG_DB:-letta}
    # Ensure this service exposes its network endpoint
    exposes:
      - port: 5432
        as: 5432
        internal: true
        global: true

  letta_server:
    dockerComposeFile: railway-compose.yaml
    dockerComposeService: letta_server
    dependsOn:
      - service: letta_db_service
        condition: HEALTHY
    envs:
      - key: LETTA_PG_URI
        value: postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@${{service.letta_db_service.PRIVATE_DOMAIN}}:5432/${POSTGRES_DB}
      - key: LETTA_DB_HOST
        value: ${{service.letta_db_service.PRIVATE_DOMAIN}}
    healthcheckPath: /
    healthcheckTimeout: 100

  pgadmin:
    dockerComposeFile: railway-compose.yaml
    dockerComposeService: pgadmin
    dependsOn:
      - service: letta_db_service
        condition: HEALTHY
    envs:
      - key: PGADMIN_DEFAULT_EMAIL
        sync: false
        value: ${PGADMIN_DEFAULT_EMAIL:-admin@letta.ai}
      - key: PGADMIN_DEFAULT_PASSWORD
        sync: false
        value: ${PGADMIN_DEFAULT_PASSWORD:-admin}
      - key: PGADMIN_LISTEN_PORT
        value: 80 