[build]
builder = "DOCKERFILE"
dockerfile = "Dockerfile"
buildCommand = "pip install -e ."

[deploy]
healthcheckPath = "/"
healthcheckTimeout = 100
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10

[volumes.postgresql]
path = "/data/postgresql"
mountPath = "/var/lib/postgresql/data"
persistent = true 